- name: Create a custom eventlog
  hosts: HOST-01
  vars:
    - iis_website_name: yourappname
  tasks:
    - name: Esnure the ssl folder exists
      ansible.windows.win_file:
        path: C:\temp\ssl
        state: directory
      become: true


    - name: Copy ssl certificate
      ansible.windows.win_copy:
        src: yourcert.pfx
        dest: 'C:\temp\yourcert.pfx'
      become: true

    - name: Import the ssl certificate
      ansible.windows.win_certificate_store:
        path: 'C:\temp\yourcert.pfx'
        password: 'WebAS'
        store_location: LocalMachine
        key_storage: machine
        state: present
      register: cert_import

    - name: Configure HTTPS binding for IIS
      community.windows.win_iis_webbinding:
        name: '{{ iis_website_name }}'
        protocol: 'https'
        port: 443
        certificate_hash: '{{ cert_import.thumbprints[0] }}'
        state: present
