- name: Reboot server
  hosts: all

  tasks:
    - name: Reboot the server
      ansible.windows.win_reboot:
        reboot_timeout: 600
        test_command: whoami
        pre_reboot_delay: 0
        post_reboot_delay: 0

