---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-volume
  labels:
    storage.k8s.io/name: nfs
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  storageClassName: ""
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 172.27.235.105
    path: /srv/nfs/kubedata
    readOnly: false