---
apiVersion: v1
kind: Service
metadata:
  name: nginx-php
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: nginx-php
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer
